// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD211tIryYvIsUqhh9-eCH-mO7bATY7a9Y',
    appId: '1:179287473502:web:4aea9fbf01e4b7e4d6a3cf',
    messagingSenderId: '179287473502',
    projectId: 'releaf-app-11021',
    authDomain: 'releaf-app-11021.firebaseapp.com',
    storageBucket: 'releaf-app-11021.firebasestorage.app',
    measurementId: 'G-KCWZG8H77G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuKd_Hd4X5TkbakAsPT0Zn0hblG6zvev4',
    appId: '1:179287473502:android:2e8e58b60b40b863d6a3cf',
    messagingSenderId: '179287473502',
    projectId: 'releaf-app-11021',
    storageBucket: 'releaf-app-11021.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZo0Zf2fbc3-J1p9LELdocetaoFlzUn4o',
    appId: '1:179287473502:ios:cb226e9ee0adafc0d6a3cf',
    messagingSenderId: '179287473502',
    projectId: 'releaf-app-11021',
    storageBucket: 'releaf-app-11021.firebasestorage.app',
    iosBundleId: 'com.example.releafApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZo0Zf2fbc3-J1p9LELdocetaoFlzUn4o',
    appId: '1:179287473502:ios:cb226e9ee0adafc0d6a3cf',
    messagingSenderId: '179287473502',
    projectId: 'releaf-app-11021',
    storageBucket: 'releaf-app-11021.firebasestorage.app',
    iosBundleId: 'com.example.releafApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD211tIryYvIsUqhh9-eCH-mO7bATY7a9Y',
    appId: '1:179287473502:web:da4c2aef6140083fd6a3cf',
    messagingSenderId: '179287473502',
    projectId: 'releaf-app-11021',
    authDomain: 'releaf-app-11021.firebaseapp.com',
    storageBucket: 'releaf-app-11021.firebasestorage.app',
    measurementId: 'G-RS9C49B44D',
  );
}
